{% set name = "pydantic-ai" %}
{% set version = "2.45.0" %}

package:
  name: {{ name }}-split
  version: {{ version }}

source:
  - url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
    sha256: e2ca1813003628203fd827b20c0dfc5ddb7bd3fb0cba30becb01a9070abb239c
    folder: pydantic-ai/
  - url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}-slim/{{ name.replace('-', '_') }}_slim-{{ version }}.tar.gz
    sha256: 34cf5216ebe05cb3d343129bb24a1bd011c66e89dd620f00afa982bd2484e3bf
    folder: pydantic-ai-slim/
  - url: https://pypi.org/packages/source/{{ name[0] }}/{{ name.split('-')[0] }}-graph/{{ name.split('-')[0] }}_graph-{{ version }}.tar.gz
    sha256: c07e8cee55f25d79ea2ea55de67fc67d0353ec2807e3a1328f42995edf022c23
    folder: pydantic-graph/
  - url: https://pypi.org/packages/source/{{ name[0] }}/{{ name.split('-')[0] }}-evals/{{ name.split('-')[0] }}_evals-{{ version }}.tar.gz
    sha256: 1ee1064036d2213155819a90c0edebfb2f8b446ad20abb9e54e279f3c59a9ac5
    folder: pydantic-evals/

build:
  number: 0

requirements:
  host:
    - python
  run:
    - python

outputs:
  - name: pydantic-graph
    version: {{ version }}
    script: build_base.sh  # [not win]
    script: build_base.bat  # [win]
    build:
      number: 1
      skip: true  # [py<310]
      script_env:
        - OUTPUT_NAME=pydantic-graph
    requirements:
      host:
        - python
        - pip
        - hatchling
        - uv-dynamic-versioning >=0.7.0
      run:
        - python
        - anyio >=4.7.0
        - logfire-api >=3.14.1
        - pydantic >=2.12
        - typing-inspection >=0.4.0
    test:
      imports:
        - pydantic_graph
      commands:
        - pip check
      requires:
        - pip
    about:
      license_file: pydantic-graph/LICENSE
  - name: pydantic-ai-slim
    version: {{ version }}
    script: build_base.sh  # [not win]
    script: build_base.bat  # [win]
    build:
      number: 0
      skip: true  # [py<310]
      script_env:
        - OUTPUT_NAME=pydantic-ai-slim
    requirements:
      host:
        - python
        - pip
        - hatchling
        - uv-dynamic-versioning >=0.7.0
      run:
        - python
        - anyio >=4.7.0
        - griffelib >=2.0
        - httpx2 >=2.7
        - pydantic >=2.12
        - {{ pin_subpackage('pydantic-graph', exact=True) }}
        - exceptiongroup >=1.2.2  # [py<311]
        - opentelemetry-api >=1.28.0
        - typing-inspection >=0.4.0
        - genai-prices >=0.1.6
    test:
      imports:
        - pydantic_ai
      commands:
        - pip check
      requires:
        - pip
    about:
      license_file: pydantic-ai-slim/LICENSE
  - name: pydantic-ai
    version: {{ version }}
    script: build_base.sh  # [not win]
    script: build_base.bat  # [win]
    build:
      number: 0
      skip: true  # [py<310]
      script_env:
        - OUTPUT_NAME=pydantic-ai
    requirements:
      host:
        - python
        - pip
        - hatchling
        - uv-dynamic-versioning >=0.7.0
      run:
        - python
        - {{ pin_subpackage('pydantic-ai-slim', exact=True) }}
    test:
      imports:
        - pydantic_ai
      commands:
        - pip check
      requires:
        - pip
    about:
      license_file: pydantic-ai/LICENSE
  - name: pydantic-evals
    version: {{ version }}
    script: build_base.sh  # [not win]
    script: build_base.bat  # [win]
    build:
      number: 0
      skip: true  # [py<310]
      script_env:
        - OUTPUT_NAME=pydantic-evals
    requirements:
      host:
        - python
        - pip
        - hatchling
        - uv-dynamic-versioning >=0.7.0
      run:
        - python
        - rich >=13.9.4
        - logfire-api >=3.14.1
        - pydantic >=2.12
        - {{ pin_subpackage('pydantic-ai-slim', exact=True) }}
        - anyio >=4.7.0
        - pyyaml >=6.0.2
    test:
      imports:
        - pydantic_evals
      commands:
        - pip check
      requires:
        - pip
    about:
      license_file: pydantic-evals/LICENSE

about:
  home: https://pydantic.dev/docs/ai/overview/
  license: MIT
  license_family: MIT
  summary: Agent Framework / shim to use Pydantic with LLMs.
  description: |
    PydanticAI is a Python agent framework designed to make it less painful
    to build production grade applications with Generative AI.
  dev_url: https://github.com/pydantic/pydantic-ai
  doc_url: https://pydantic.dev/docs/ai/overview/

extra:
  recipe-maintainers:
    - rxm7706
    - mariusvniekerk
  skip-lints:
    - missing_python_build_tool
    - wrong_output_script_key
    - missing_pip_check
