{% set name = "pydantic-ai" %}
{% set name_slim = "pydantic-ai-slim" %}
{% set version = "2.33.0" %}

package:
  name: {{ name }}-split
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name_slim[0] }}/{{ name_slim }}/{{ name_slim.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 0709cb6de91cd9f8faa986676f1f2e2283ae27af3c41e69f08411cf12d7535ed

build:
  number: 0

requirements:
  host:
    - python
  run:
    - python

outputs:
  - name: {{ name_slim }}
    version: {{ version }}
    build:
      skip: true  # [py<310]
      script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
    requirements:
      host:
        - pip
        - python
        - hatchling
        - uv-dynamic-versioning >=0.7.0
      run:
        - python
        - anyio >=4.7.0
        - griffelib >=2.0
        - httpx2 >=2.7
        - pydantic >=2.12
        - pydantic-graph =={{ version }}
        - exceptiongroup >=1.2.2  # [py<311]
        - opentelemetry-api >=1.28.0
        - typing-inspection >=0.4.0
        - genai-prices >=0.1.0
    test:
      imports:
        - pydantic_ai
      commands:
        - pip check
      requires:
        - pip
  - name: {{ name }}
    version: {{ version }}
    build:
      skip: true  # [py<310]
    requirements:
      host:
        - python
      run:
        - python
        - {{ pin_subpackage('pydantic-ai-slim', exact=True) }}
    test:
      imports:
        - pydantic_ai
      commands:
        - pip check
      requires:
        - pip

about:
  home: https://pydantic.dev/docs/ai/overview/
  license: MIT
  license_file: LICENSE
  license_family: MIT
  summary: Agent Framework / shim to use Pydantic with LLMs
  description: |
    PydanticAI is a Python agent framework designed to make it less painful
    to build production grade applications with Generative AI.
  dev_url: https://github.com/pydantic/pydantic-ai
  doc_url: https://pydantic.dev/docs/ai/overview/

extra:
  recipe-maintainers:
    - rxm7706
    - mariusvniekerk
  skip-lints:
    - missing_python_build_tool
    - wrong_output_script_key
    - missing_pip_check
